from . import localiza_tecnico_formulario
from . import localiza_guardia_asignacion
from . import localiza_guardia_puesto_servicio
from . import localiza_rrhh_planilla_pago
from . import localiza_guardia_puesto
from . import localiza_guardia_turno
from . import localiza_tecnico
from . import localiza_guardia_asignacion_stage
from . import localiza_rrhh_empleado_linea
from . import localiza_rrhh_empleado_referencia
from . import localiza_rrhh_empleado_linea_aux
from . import localiza_rrhh_empleado_linea_extra
from . import localiza_rrhh_empleado_estudio
from . import localiza_rrhh_empleado_experiencia
from . import localiza_rrhh_empleado_familia
from . import localiza_rrhh_empleado_documento
from . import localiza_rrhh_empleado_contacto_emergencia
from . import extension_hr_employee
from . import extension_hr_payslip
