# -*- coding: utf-8 -*-
from odoo import models, fields, api


class LocalizaExtHr_employee(models.Model):
    _inherit = "hr.employee"

    nivel_de_estudios = fields.Char(string="Nivel de estudios", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    # estudios: One2many original omitido hasta definir inverse_name.
    # estudios_tecnicos: One2many original omitido hasta definir inverse_name.
    campo_de_estudio = fields.Char(string="Campo de estudio")
    centro_de_estudios = fields.Char(string="Centro de Estudios")
    a_prestado_servicio_militar = fields.Char(string="A prestado servicio militar: ", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    abril = fields.Float(string="Abril")
    actividades_deportivas_religiosas_o_culturale = fields.Text(string="Actividades deportivas, religiosas o culturales:")
    actualizar = fields.Boolean(string="Actualizar ")
    actualizar_fechas = fields.Boolean(string="Actualizar Fechas")
    afiliacion_del_igss = fields.Binary(string="AFILIACIÓN DEL IGSS")
    filename_for_binary_field_bkb7a = fields.Char(string="Filename for x_studio_binary_field_BKb7a")
    aguinaldo = fields.Float(string="Aguinaldo")
    aguinaldo_al = fields.Date(string="Aguinaldo al: ")
    aguinaldo_del = fields.Date(string="Aguinaldo del: ")
    alergias = fields.Char(string="¿Alergías?", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    fecha_de_emision_a_p = fields.Binary(string="Fecha de Emisión A/P:")
    filename_for_binary_field_h9jqn = fields.Char(string="Filename for x_studio_binary_field_H9jQn")
    antecedentes_policiacos = fields.Binary(string="ANTECEDENTES POLICIACOS")
    filename_for_binary_field_3lq4o = fields.Char(string="Filename for x_studio_binary_field_3lq4O")
    ano_de_graduacion = fields.Char(string="Año de graduación:")
    ano_de_graduacion_2 = fields.Char(string="Año de graduación:")
    ano_de_graduacion_3 = fields.Char(string="Año de graduación: ")
    ano_de_graduacion_4 = fields.Char(string="Año de graduación:")
    apellido_de_casada = fields.Char(string="Apellido de Casada")
    bebe = fields.Char(string="Bebe:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    bonificacion_incentivo = fields.Float(string="Bonificación Incentivo")
    bono_14 = fields.Float(string="BONO 14")
    bono_14_al = fields.Date(string="Bono 14 al:")
    bono_14_del = fields.Date(string="Bono 14 del:")
    bono_dto = fields.Float(string=" Bono DTO ")
    basicos = fields.Char(string="Básicos:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    carrera = fields.Char(string="Carrera")
    carrera_tecnica = fields.Char(string="Carrera Técnica:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    certificado_de_nacimiento = fields.Binary(string="CERTIFICADO DE NACIMIENTO")
    filename_for_binary_field_68cx0 = fields.Char(string="Filename for x_studio_binary_field_68cx0")
    certificado_medico = fields.Binary(string="CERTIFICADO MEDICO")
    filename_for_binary_field_uyijq = fields.Char(string="Filename for x_studio_binary_field_UyIjq")
    compania = fields.Char(string="Compañía:")
    constancia_de_vacuanacion = fields.Binary(string="CONSTANCIA DE VACUANACIÓN")
    filename_for_binary_field_yxqav = fields.Char(string="Filename for x_studio_binary_field_yxqAv")
    contrato = fields.Binary(string="Contrato")
    filename_for_binary_field_h74v4 = fields.Char(string="Filename for x_studio_binary_field_H74V4")
    credencial_de_digessp = fields.Char(string="Credencial de DIGESSP:")
    credencial_digessp = fields.Binary(string="CREDENCIAL DIGESSP")
    filename_for_binary_field_lytte = fields.Char(string="Filename for x_studio_binary_field_lytte")
    cuales = fields.Char(string="¿Cuales?")
    cuales_2 = fields.Char(string="¿Cuales?")
    cuales_3 = fields.Char(string="¿Cuales?")
    dias_de_aguinaldo = fields.Integer(string="Días de Aguinaldo")
    dias_de_bono_14 = fields.Integer(string="Días de Bono 14:")
    dias_de_indemnizacion = fields.Integer(string="Días de indemnización:")
    dias_de_vacaciones = fields.Integer(string="Días de Vacaciones: ")
    dias_de_vacaciones_a_pagar = fields.Integer(string="Días de Vacaciones a pagar ")
    dias_establecido = fields.Integer(string="Días establecido")
    de_ser_otra_cual = fields.Char(string="De ser otra ¿Cual?")
    departamento = fields.Char(string="Departamento:")
    departamento_de_domicilio = fields.Many2one("localiza.geo.departamento", string="Departamento de Domicilio:", ondelete="set null")
    departamento_de_emision_del_documento = fields.Many2one("localiza.geo.departamento", string="Departamento de Emisión del Documento", ondelete="set null")
    departamento_de_nacimiento = fields.Many2one("localiza.geo.departamento", string="Departamento de Nacimiento", ondelete="set null")
    departamento_que_labora = fields.Many2one("localiza.geo.departamento", string="Departamento que labora", ondelete="set null")
    diciembre = fields.Float(string="Diciembre")
    direccion_completa_del_puesto_de_servicio = fields.Char(string="Dirección completa del puesto de servicio")
    diversificado = fields.Char(string="Diversificado:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    documento_de_identificacion = fields.Char(string="Documento de Identificación:")
    domicilio = fields.Char(string="Domicilio:")
    domicilioq = fields.Char(string="Domicilioq:")
    dpi_adjunto = fields.Binary(string="DPI Adjunto")
    filename_for_binary_field_fvuqe = fields.Char(string="Filename for x_studio_binary_field_fvuQE")
    e_mail_personal = fields.Char(string="E-mail personal")
    edad = fields.Char(string="Edad")
    enero = fields.Float(string="Enero")
    especificar = fields.Text(string="Especificar: ")
    esta_asegurado = fields.Char(string="¿Esta Asegurado?", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    esta_asignado_a_un_puesto = fields.Boolean(string="Esta asignado a un Puesto ")
    establecimiento = fields.Char(string="Establecimiento")
    estado_civil = fields.Char(string="Estado Civil:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    estado_de_la_persona = fields.Char(string="Estado de la Persona", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    estado_de_la_persona_2 = fields.Char(string="Estado de la Persona", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    estatura_en_cm = fields.Char(string="Estatura en cm: ")
    estudia_actualmente = fields.Char(string="¿Estudia actualmente?", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    explique_deuda = fields.Text(string="Explique deuda: ")
    extendida_en = fields.Char(string="Extendida en:")
    febrero = fields.Float(string="Febrero")
    fecha_de_emision_a_p_2 = fields.Date(string="Fecha de Emisión A/P:")
    fecha_de_emision_a_p_3 = fields.Date(string="Fecha de Emisión A/P:")
    fecha_de_emision_c_m = fields.Date(string="Fecha de Emisión C/M")
    fecha_de_emision_c_n = fields.Date(string="Fecha de Emisión C/N:")
    fecha_de_emision_digessp = fields.Date(string="Fecha de Emisión DIGESSP")
    fecha_de_emision_dpi = fields.Date(string="Fecha de Emisión DPI:")
    fecha_de_emision_nasp = fields.Date(string="Fecha de Emisión  NASP")
    fecha_de_emision_ornato = fields.Date(string="Fecha de Emisión Ornato")
    fecha_de_emision_renas = fields.Date(string="Fecha de Emisión  Renas")
    fecha_de_emision_tarjeta_de_salud = fields.Date(string="Fecha de Emisión Tarjeta de Salud")
    fecha_de_alta = fields.Date(string="Fecha de Alta:")
    fecha_de_baja = fields.Date(string="Fecha de Baja:")
    fecha_de_vencimiento_a_p = fields.Date(string="Fecha de Vencimiento A/P:")
    fecha_de_vencimiento_a_p_2 = fields.Date(string="Fecha de Vencimiento A/P:")
    fecha_de_vencimiento_c_m = fields.Date(string="Fecha de Vencimiento C/M")
    fecha_de_vencimiento_c_n = fields.Date(string="Fecha de Vencimiento C/N:")
    fecha_de_vencimiento_digessp = fields.Date(string="Fecha de Vencimiento DIGESSP")
    fecha_de_vencimiento_dpi = fields.Date(string="Fecha de Vencimiento DPI:")
    fecha_de_vencimiento_naps = fields.Date(string="Fecha de vencimiento NAPS")
    fecha_de_vencimiento_ornato = fields.Date(string="Fecha de Vencimiento Ornato")
    fecha_de_vencimiento_renas = fields.Date(string="Fecha de Vencimiento renas")
    fecha_de_vencimiento_tarjeta_de_salud = fields.Date(string="Fecha de Vencimiento Tarjeta de Salud")
    fuma = fields.Char(string="Fuma:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    ha_estado_enfermo_de_gravedad = fields.Char(string="Ha estado enfermo de gravedad: ", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    horarios = fields.Char(string="Horarios")
    id_de_la_credencial_de_portacion_de_af = fields.Char(string="ID de la credencial de portación de AF")
    idiomas = fields.Char(string="Idiomas", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    igss = fields.Float(string=" IGSS")
    impedimento_fisico = fields.Text(string="Impedimento físico:")
    indemnizacion = fields.Float(string="Indemnización")
    indemnizacion_al = fields.Date(string="Indemnización al:")
    indemnizacion_del = fields.Date(string="Indemnización del:")
    informacion_del_contrato = fields.Text(string="Información del Contrato ")
    institucion = fields.Char(string="Institución:")
    institucion_2 = fields.Char(string="Institución: ")
    institucion_3 = fields.Char(string="Institución:")
    institucion_4 = fields.Char(string="Institución: ")
    institucion_5 = fields.Char(string="Institución: ")
    isr = fields.Float(string=" ISR ")
    jefe_inmediato = fields.Char(string="Jefe inmediato:")
    licencia_de_conducir = fields.Char(string="Licencia de conducir:")
    licencia_de_conducir_2 = fields.Char(string="Licencia de conducir:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    licencia_de_portacion_de_armas = fields.Char(string="Licencia de portación de armas: ", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    licencia_de_tenencia_de_arma = fields.Char(string="Licencia de Tenencia de Arma:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    liquido_a_recibir = fields.Float(string="Liquido a Recibir")
    # campo: One2many original omitido hasta definir inverse_name.
    nombre_del_puesto_del_servicio = fields.Many2one("localiza.guardia.puesto.servicio", string="NOMBRE DEL PUESTO DEL  SERVICIO", ondelete="set null")
    marca_y_modelo_del_vehiculo = fields.Char(string="Marca y modelo del vehículo:")
    marzo = fields.Float(string="Marzo")
    mayo = fields.Float(string="Mayo")
    motivo_de_retiro = fields.Char(string="Motivo de retiro:")
    municipio = fields.Char(string="Municipio:")
    municipio_de_domicilio = fields.Many2one("localiza.geo.municipio", string="Municipio de Domicilio", ondelete="set null")
    municipio_de_nacimiento = fields.Many2one("localiza.geo.municipio", string="Municipio de Nacimiento", ondelete="set null")
    municipio_emisor = fields.Many2one("localiza.geo.municipio", string="Municipio Emisor", ondelete="set null")
    municipio_que_labora = fields.Many2one("localiza.geo.municipio", string="Municipio  que labora", ondelete="set null")
    n_de_dpi = fields.Char(string="N° de DPI:")
    nasp = fields.Binary(string="NASP")
    filename_for_binary_field_0wsaz = fields.Char(string="Filename for x_studio_binary_field_0wsaZ")
    nit = fields.Char(string="NIT: ")
    nit_adjunto = fields.Binary(string="NIT Adjunto")
    filename_for_binary_field_r6j6s = fields.Char(string="Filename for x_studio_binary_field_R6J6S")
    nivel_de_estudios_alcanzado = fields.Char(string="Nivel de estudios alcanzado:")
    numero_de_afiliacion_del_igss = fields.Char(string="Número de Afiliación del IGSS ")
    n_de_dpi_2 = fields.Integer(string="N° de DPI:")
    numero_de_edades_de_hijos = fields.Char(string="Número de edades de hijos: ")
    no_de_igss = fields.Char(string="No. De IGSS:")
    nombre_de_la_madre_edad_y_ocupacion = fields.Text(string="Nombre de la Madre, edad y ocupación:")
    nombre_del_conyuge = fields.Char(string="Nombre del Cónyuge:")
    nombre_del_padre_edad_y_ocupacion = fields.Text(string="Nombre del Padre, edad y ocupación:")
    # nuevas_lineas: One2many original omitido hasta definir inverse_name.
    # experiencia_laboral: One2many original omitido hasta definir inverse_name.
    # nuevas_lineas_2: One2many original omitido hasta definir inverse_name.
    # nuevas_lineas_3: One2many original omitido hasta definir inverse_name.
    # datos_familiares: One2many original omitido hasta definir inverse_name.
    # nuevas_lineas_4: One2many original omitido hasta definir inverse_name.
    # nuevas_lineas_5: One2many original omitido hasta definir inverse_name.
    # nuevas_lineas_6: One2many original omitido hasta definir inverse_name.
    ornato = fields.Binary(string="ORNATO")
    filename_for_binary_field_s490y = fields.Char(string="Filename for x_studio_binary_field_S490Y")
    otros_descuentos = fields.Float(string="Otros Descuentos")
    padece_algun_impedimento_total_o_parcial = fields.Char(string="Padece algún impedimento total o parcial", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    padece_alguna_de_las_siguientes_enfermedades = fields.Char(string="Padece alguna de las siguientes enfermedades:  ", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    para_indemnizacion = fields.Float(string="PARA INDEMNIZACIÓN")
    peso = fields.Char(string="Peso:")
    posee_vehiculo = fields.Char(string="Posee vehículo:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    primaria = fields.Char(string="Primaria:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    primer_apellido = fields.Char(string="Primer Apellido")
    primer_nombre = fields.Char(string="Primer Nombre")
    profesion = fields.Char(string="Profesión:")
    promedio = fields.Float(string="PROMEDIO")
    puesto = fields.Char(string="Puesto:")
    renas = fields.Binary(string="RENAS")
    filename_for_binary_field_qnefj = fields.Char(string="Filename for x_studio_binary_field_qNefJ")
    residencia = fields.Char(string="Residencia:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    salario = fields.Float(string="Salario:")
    salario_2 = fields.Float(string="Salario: ")
    segundo_apellido = fields.Char(string="Segundo Apellido")
    segundo_nombre = fields.Char(string="Segundo Nombre")
    graduado_universitario = fields.Char(string="Graduado Universitario:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    semestres_aprobados = fields.Char(string="Semestres aprobados", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    sexo = fields.Char(string="Sexo: ", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    tarjeta_de_pulmones = fields.Binary(string="TARJETA DE PULMONES")
    filename_for_binary_field_hivyb = fields.Char(string="Filename for x_studio_binary_field_HIvYB")
    tarjeta_de_salud = fields.Binary(string="TARJETA DE SALUD")
    filename_for_binary_field_wlp2w = fields.Char(string="Filename for x_studio_binary_field_wLP2w")
    telefono = fields.Char(string="Teléfono")
    telefono_de_casa = fields.Char(string="Teléfono de casa:")
    telefono_de_contacto = fields.Char(string="Teléfono de contacto: ")
    tercer_nombre = fields.Text(string="Tercer Nombre")
    tiempo_de_vivir_alli = fields.Char(string="Tiempo de vivir allí: ")
    tiempo_laborado = fields.Char(string="Tiempo laborado: ")
    tiene_alguna_deuda = fields.Char(string="Tiene alguna deuda: ", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    tipo_de_documento = fields.Char(string="Tipo de Documento", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    tipo_de_sangre = fields.Char(string="Tipo de sangre:")
    tipo_de_sangre_2 = fields.Char(string="Tipo de sangre:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    consume_medicamentos = fields.Char(string="Consume Medicamentos:", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    total = fields.Float(string="TOTAL")
    total_a_liquidar = fields.Float(string="Total a Liquidar")
    titulo = fields.Binary(string="Título")
    titulo_2 = fields.Binary(string="Título")
    filename_for_binary_field_dfgm1 = fields.Char(string="Filename for x_studio_binary_field_DfGM1")
    filename_for_binary_field_9xuuh = fields.Char(string="Filename for x_studio_binary_field_9xUuh")
    vacaciones = fields.Float(string="Vacaciones")
    vacaciones_al = fields.Date(string="Vacaciones al:")
    vacaciones_del = fields.Date(string="Vacaciones del:")
    vacuna_covid_19_dosis = fields.Char(string="Vacuna COVID-19 dosis:")
    zona = fields.Char(string="Zona", help="Campo convertido desde selección de Studio; revisar opciones originales antes de producción.")
    zona_2 = fields.Char(string="Zona")
